# Generated by Django 5.1.5 on 2025-01-19 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth0_user_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_available', models.IntegerField()),
                ('units_sold', models.IntegerField()),
                ('customer_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('optimized_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageProduct.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('version', models.IntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageProduct.product')),
            ],
            options={
                'unique_together': {('product', 'version')},
            },
        ),
    ]
