# Generated by Django 5.1.5 on 2025-01-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auth0_user_id',
            field=models.CharField(max_length=255),
        ),
    ]
