# Generated by Django 4.2.18 on 2025-01-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusers',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokenusers',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
